name: PaymentServiceNet
version: "3.9"

services:
  movies:
    image: ${DOCKER_REGISTRY-}movies
    build:
      context: .        
      dockerfile: PaymentServiceNet/Dockerfile
    ports:
      - "8000:80"
    environment:
      ConnectionStrings__ConexionSQL: "Server=host.docker.internal,1433;Database=PaymentServiceNetNet7;User Id=sa;Password=sasasa;Encrypt=False"
